// Code generated by github.com/ycl2018/go-conv DO NOT EDIT.

package basic

import (
	"github.com/ycl2018/go-conv/testdata/a"
	"github.com/ycl2018/go-conv/testdata/b"
	"unsafe"
)

func ABasicToPtrBBasic(src a.Basic) (dst *b.Basic) {
	dst = new(b.Basic)
	*dst = b.Basic(src)
	return
}
func PtrABasicPtrToPtrBBasic(src *a.BasicPtr) (dst *b.Basic) {
	if src != nil {
		dst = new(b.Basic)
		dst.Bool = *src.Bool
		dst.Int = *src.Int
		dst.Int8 = *src.Int8
		dst.Int16 = *src.Int16
		dst.Int32 = *src.Int32
		dst.Int64 = *src.Int64
		dst.Uint = *src.Uint
		dst.Uint8 = *src.Uint8
		dst.Uint16 = *src.Uint16
		dst.Uint32 = *src.Uint32
		dst.Uint64 = *src.Uint64
		dst.Uintptr = *src.Uintptr
		dst.Float32 = *src.Float32
		dst.Float64 = *src.Float64
		dst.Complex64 = *src.Complex64
		dst.Complex128 = *src.Complex128
		dst.String = *src.String
		dst.UnsafePointer = unsafe.Pointer(src.UnsafePointer)
		dst.Byte = *src.Byte
		dst.Rune = *src.Rune
	}
	return
}
func PtrABasicPtrToPtrBBasicPtr(src *a.BasicPtr) (dst *b.BasicPtr) {
	dst = (*b.BasicPtr)(src)
	return
}
func PtrABasicToBBasic(src *a.Basic) (dst b.Basic) {
	dst = b.Basic(*src)
	return
}
func PtrABasicToPtrBBasic(src *a.Basic) (dst *b.Basic) {
	dst = (*b.Basic)(src)
	return
}
func PtrABasicToPtrBBasicPtr(src *a.Basic) (dst *b.BasicPtr) {
	if src != nil {
		dst = new(b.BasicPtr)
		dst.Bool = new(bool)
		*dst.Bool = src.Bool
		dst.Int = new(int)
		*dst.Int = src.Int
		dst.Int8 = new(int8)
		*dst.Int8 = src.Int8
		dst.Int16 = new(int16)
		*dst.Int16 = src.Int16
		dst.Int32 = new(int32)
		*dst.Int32 = src.Int32
		dst.Int64 = new(int64)
		*dst.Int64 = src.Int64
		dst.Uint = new(uint)
		*dst.Uint = src.Uint
		dst.Uint8 = new(uint8)
		*dst.Uint8 = src.Uint8
		dst.Uint16 = new(uint16)
		*dst.Uint16 = src.Uint16
		dst.Uint32 = new(uint32)
		*dst.Uint32 = src.Uint32
		dst.Uint64 = new(uint64)
		*dst.Uint64 = src.Uint64
		dst.Uintptr = new(uintptr)
		*dst.Uintptr = src.Uintptr
		dst.Float32 = new(float32)
		*dst.Float32 = src.Float32
		dst.Float64 = new(float64)
		*dst.Float64 = src.Float64
		dst.Complex64 = new(complex64)
		*dst.Complex64 = src.Complex64
		dst.Complex128 = new(complex128)
		*dst.Complex128 = src.Complex128
		dst.String = new(string)
		*dst.String = src.String
		dst.UnsafePointer = (*unsafe.Pointer)(src.UnsafePointer)
		dst.Byte = new(byte)
		*dst.Byte = src.Byte
		dst.Rune = new(rune)
		*dst.Rune = src.Rune
	}
	return
}
func init() {
	BasicPointerToBasic = PtrABasicPtrToPtrBBasic
	BasicPointerToBasicPointer = PtrABasicPtrToPtrBBasicPtr
	BasicPtrToBasic = PtrABasicToBBasic
	BasicToBasic = PtrABasicToPtrBBasic
	BasicToBasicPointer = PtrABasicToPtrBBasicPtr
	BasicToBasicPtr = ABasicToPtrBBasic
}
