// Code generated by github.com/ycl2018/go-conv DO NOT EDIT.

package cast

import (
	"github.com/ycl2018/go-conv/testdata/a"
	"github.com/ycl2018/go-conv/testdata/b"
)

func ACastfloat32ToPtrBCastPtrint(src a.Cast[float32]) (dst *b.Cast[*int]) {
	dst = new(b.Cast[*int])
	dst.Name = new(int)
	*dst.Name = int(src.Name)
	return
}
func ACastfloat32ToPtrBCastint(src a.Cast[float32]) (dst *b.Cast[int]) {
	dst = new(b.Cast[int])
	dst.Name = int(src.Name)
	return
}
func PtrACastintToPtrBCastfloat32(src *a.Cast[int]) (dst *b.Cast[float32]) {
	if src != nil {
		dst = new(b.Cast[float32])
		dst.Name = float32(src.Name)
	}
	return
}
func PtrACastintToPtrBCastuint(src *a.Cast[int]) (dst *b.Cast[uint]) {
	if src != nil {
		dst = new(b.Cast[uint])
		dst.Name = uint(src.Name)
	}
	return
}
func init() {
	FloatToInt = ACastfloat32ToPtrBCastint
	FloatToIntPtr = ACastfloat32ToPtrBCastPtrint
	IntToFloat = PtrACastintToPtrBCastfloat32
	IntToUint = PtrACastintToPtrBCastuint
}
