// Code generated by github.com/ycl2018/go-conv DO NOT EDIT.

package conflict

import (
	"github.com/ycl2018/go-conv/testdata/a"
	"github.com/ycl2018/go-conv/testdata/b"
)

func PtrABasicToPtrBBasic(src *a.Basic) (dst *b.Basic) {
	dst = (*b.Basic)(src)
	return
}
func PtrABasicToPtrBBasic1(src *a.Basic) (dst *b.Basic) {
	if src != nil {
		dst = new(b.Basic)
		dst.Bool = src.Bool
		dst.Int = src.Int
		dst.Int8 = src.Int8
		dst.Int16 = src.Int16
		dst.Int32 = src.Int32
		dst.Int64 = src.Int64
		dst.Uint = src.Uint
		// apply ignore option on src.Uint8
		// apply ignore option on src.Uint16
		dst.Uint32 = src.Uint32
		dst.Uint64 = src.Uint64
		dst.Uintptr = src.Uintptr
		dst.Float32 = src.Float32
		dst.Float64 = src.Float64
		dst.Complex64 = src.Complex64
		dst.Complex128 = src.Complex128
		dst.String = src.String
		dst.UnsafePointer = src.UnsafePointer
		dst.Byte = src.Byte
		dst.Rune = src.Rune
	}
	return
}
func init() {
	BasicToBasic = PtrABasicToPtrBBasic
	BasicToBasicOmit2 = PtrABasicToPtrBBasic1
}
