// Code generated by github.com/ycl2018/go-conv DO NOT EDIT.
// +build !goconv_gen

package special

import "time"

func CopyTimeTimeToTimeTime(src time.Time) (dst time.Time) {
	dst = src
	return
}
func init() {
	timeToTime = CopyTimeTimeToTimeTime
}
