// Code generated by github.com/ycl2018/go-conv DO NOT EDIT.

package cases

import (
	"github.com/ycl2018/go-conv/testdata/a"
	"github.com/ycl2018/go-conv/testdata/b"
)

func PtrABasicToPtrBBasic(src *a.Basic) (dst *b.Basic) {
	dst = (*b.Basic)(src)
	return
}
func init() {
	BasicToBasic = PtrABasicToPtrBBasic
}
